theme: jekyll-theme-cayman
name: ennc0d3, code @ (k)night

permalink: /blog/:year/:month/:day/:title
twitter_username: ennmail
github_username: ennc0d3

# Markdown Processing
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
highlighter: rouge
  input: GFM
safe: true
incremental: false
gist:
  noscript: false