name: ennc0d3, code @ (k)night
title: Welcome to the ennc0d3's homepage!
description: A blog, a scratch pad, whatever else

theme: jekyll-theme-cayman

permalink: /blog/:year/:month/:day/:title
twitter_username: ennmail
github_username: ennc0d3

# Markdown Processing
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

safe: true
incremental: false
gist:
  noscript: false
