theme: jekyll-theme-cayman
name: ennc0d3, code @ (k)night
markdown: kramdown

permalink: /blog/:year/:month/:day/:title
twitter_username: ennmail
github_username: ennc0d3
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
  
 # Outputting
permalink: /:categories/:title/


