name: ennc0d3, code @ (k)night
title: Welcome to the ennc0d3's homepage!
description: A blog, a scratch pad, and what not!

theme: jekyll-theme-cayman

twitter_username: ennmail
github_username: ennc0d3
owner_email: ennc0d3@gmail.com

github:
  is_project_page: true
  repository_url: github.com/ennc0d3/ennc0d3.github.io
  repository_name: ennc0d3
  owner_name: Nagarajan Ganesan
  owner_url: github.com/ennc0d3

show_downloads: false
google_analytics:

safe: true
incremental: false
gist:
  noscript: false
  
  
  # Output options (more information on Jekyll's site)
timezone: "Europe/Stockholm"
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
paginate: 5

kramdown:
  input: GFM
